baseURL = "https://research.mach1.tech/"
languageCode = "en-us"
title = "Mach1 Research"
titledescription = "Spatial & Multichannel Blog"
theme = "mach1-research-blog"
copyright = "©2015 -> ©2025 Mach1, Corp."

enableGitInfo = true
enableRobotsTXT = true

# Content organization
[taxonomies]
  category = "categories"
  tag = "tags"
  
[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Tutorials"
    url = "/tutorials/"
    weight = 2
  [[menu.main]]
    name = "Glossary"
    url = "/glossary/"
    weight = 3
  [[menu.main]]
    name = "Musings"
    url = "/musings/"
    weight = 4

[markup.highlight]
  codeFences = true
  noClasses = false

[markup.goldmark.renderer]
  unsafe = true  # enable raw HTML in Markdown

[params]
  style = "auto"  # default: auto. light: light theme, dark: dark theme, auto: based on system.
  dateFormat = "January 2, 2006"  # if unset, default is "2006-01-02"
  ShowDatesOnPosts = true
  logo = "/logo.svg"
  slogan = "Defenders of the Audio Realm"
  fullRss = true # Puts entire HTML post into rss 'description' tag. If unset, default is false.
  disableSearch = true # default is false
  disableReadmoreNav = true # set true to hide prev/next navigation, default is false
  # Google Analytics 4
  googleAnalyticsID = "G-7RBPB84DPR"
  
  # Define main sections
  mainSections = ["posts", "tutorials", "musings", "glossary"]

[params.comments]
  enable = false  # En/Disable comments globally, default: false. You can always enable comments on per page.

[params.math]
  enable = false  # optional: true, false. Enable globally, default: false. You can always enable math on per page.
  use = "katex"  # option: "katex", "mathjax". default: "katex"

[params.syntax]
  use = "none"  # builtin: "prismjs", "hljs". "none" means Chroma
  theme = "xcode"
  darkTheme = "xcode-dark"  # apply this theme in dark mode

[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]
